### ISSUE TITLE
C++ build failures

### ISSUE THREAD

**Issue by bburdette** [sebpiq/node-web-audio-api#32]
I've given this a try on nixos and on arch, but I get the same failure on each when I do npm install.  It kind of looks like I might have the wrong version of a C library?  The results are below.  

My procedure:

install npm via git and make install
> git clone https://github.com/npm/npm.git
> make install (I think)

install web-audio via git, then npm install 
> git clone https://github.com/sebpiq/node-web-audio-api.git
> cd node-web-audio-api
> npm install

result: C++ compile errors.  

```
[bananapi@lemaker node-web-audio-api]$ export PYTHON=python2
[bananapi@lemaker node-web-audio-api]$ npm install
|
> speaker@0.0.10 install /home/bananapi/code/node-web-audio-api/node_modules/speaker
> node-gyp rebuild

make: Entering directory '/home/bananapi/code/node-web-audio-api/node_modules/speaker/build'
  CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
../deps/mpg123/src/output/alsa.c: In function ‘rates_match’:
../deps/mpg123/src/output/alsa.c:53:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  return actual * 100 > desired * (100 - AUDIO_RATE_TOLERANCE) &&
                      ^
../deps/mpg123/src/output/alsa.c:54:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         actual * 100 < desired * (100 + AUDIO_RATE_TOLERANCE);
                      ^
../deps/mpg123/src/output/alsa.c: In function ‘initialize_device’:
../deps/mpg123/src/output/alsa.c:78:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (i = 0; i < NUM_FORMATS; ++i) {
                ^
../deps/mpg123/src/output/alsa.c: In function ‘get_formats_alsa’:
../deps/mpg123/src/output/alsa.c:201:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (i = 0; i < NUM_FORMATS; ++i) {
                ^
  AR(target) Release/obj.target/deps/mpg123/liboutput.a
  COPY Release/liboutput.a
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cc:6:0:
../src/node_pointer.h: In function ‘v8::Handle<v8::Value> WrapPointer(void*, size_t)’:
../src/node_pointer.h:23:16: error: expected primary-expression before ‘*’ token
   node::Buffer *buf = node::Buffer::New((char *)ptr, length, wrap_pointer_cb, user_data);
                ^
../src/node_pointer.h:23:17: error: ‘buf’ was not declared in this scope
   node::Buffer *buf = node::Buffer::New((char *)ptr, length, wrap_pointer_cb, user_data);
                 ^
../src/binding.cc: At global scope:
../src/binding.cc:17:3: error: ‘uv_work_t’ does not name a type
   uv_work_t req;
   ^
../src/binding.cc:25:27: error: ‘Arguments’ does not name a type
 Handle<Value> Open (const Arguments& args) {
                           ^
In file included from ../src/binding.cc:4:0:
/home/bananapi/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> {anonymous}::Open(const int&)’:
/home/bananapi/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/binding.cc:26:15: error: within this context
   HandleScope scope;
               ^
../src/binding.cc:28:79: error: invalid types ‘const int[int]’ for array subscript
   audio_output_t *ao = reinterpret_cast<audio_output_t *>(UnwrapPointer(args[0]));
                                                                               ^
../src/binding.cc:31:32: error: invalid types ‘const int[int]’ for array subscript
   Local<Object> format = args[1]->ToObject();
                                ^
../src/binding.cc:33:30: error: ‘NewSymbol’ is not a member of ‘v8::String’
   ao->channels = format->Get(String::NewSymbol("channels"))->Int32Value(); /* channels */
                              ^
../src/binding.cc:34:26: error: ‘NewSymbol’ is not a member of ‘v8::String’
   ao->rate = format->Get(String::NewSymbol("sampleRate"))->Int32Value(); /* sample rate */
                          ^
../src/binding.cc:36:30: error: ‘NewSymbol’ is not a member of ‘v8::String’
   int bitDepth = format->Get(String::NewSymbol("bitDepth"))->Int32Value();
                              ^
../src/binding.cc:37:31: error: ‘NewSymbol’ is not a member of ‘v8::String’
   bool isSigned = format->Get(String::NewSymbol("signed"))->BooleanValue();
                               ^
../src/binding.cc:38:30: error: ‘NewSymbol’ is not a member of ‘v8::String’
   bool isFloat = format->Get(String::NewSymbol("float"))->BooleanValue();
                              ^
../src/binding.cc:72:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(Integer::New(r));
                ^
../src/binding.cc:72:36: error: no matching function for call to ‘v8::Integer::New(int&)’
   return scope.Close(Integer::New(r));
                                    ^
../src/binding.cc:72:36: note: candidate is:
In file included from ../src/binding.cc:4:0:
/home/bananapi/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/bananapi/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/binding.cc: At global scope:
../src/binding.cc:75:19: error: variable or field ‘write_async’ declared void
 void write_async (uv_work_t *);
                   ^
../src/binding.cc:75:19: error: ‘uv_work_t’ was not declared in this scope
../src/binding.cc:75:30: error: expected primary-expression before ‘)’ token
 void write_async (uv_work_t *);
                              ^
../src/binding.cc:76:19: error: variable or field ‘write_after’ declared void
 void write_after (uv_work_t *);
                   ^
../src/binding.cc:76:19: error: ‘uv_work_t’ was not declared in this scope
../src/binding.cc:76:30: error: expected primary-expression before ‘)’ token
 void write_after (uv_work_t *);
                              ^
../src/binding.cc:78:28: error: ‘Arguments’ does not name a type
 Handle<Value> Write (const Arguments& args) {
                            ^
In file included from ../src/binding.cc:4:0:
/home/bananapi/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> {anonymous}::Write(const int&)’:
/home/bananapi/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/binding.cc:79:15: error: within this context
   HandleScope scope;
               ^
../src/binding.cc:80:79: error: invalid types ‘const int[int]’ for array subscript
   audio_output_t *ao = reinterpret_cast<audio_output_t *>(UnwrapPointer(args[0]));
                                                                               ^
../src/binding.cc:81:81: error: invalid types ‘const int[int]’ for array subscript
   unsigned char *buffer = reinterpret_cast<unsigned char *>(UnwrapPointer(args[1]));
                                                                                 ^
../src/binding.cc:82:19: error: invalid types ‘const int[int]’ for array subscript
   int len = args[2]->Int32Value();
                   ^
../src/binding.cc:83:58: error: invalid types ‘const int[int]’ for array subscript
   Local<Function> callback = Local<Function>::Cast(args[3]);
                                                          ^
../src/binding.cc:90:53: error: no matching function for call to ‘v8::Persistent<v8::Function>::New(v8::Local<v8::Function>&)’
   req->callback = Persistent<Function>::New(callback);
                                                     ^
../src/binding.cc:90:53: note: candidate is:
In file included from ../src/binding.cc:4:0:
/home/bananapi/.node-gyp/0.12.0/deps/v8/include/v8.h:5809:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Function]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/home/bananapi/.node-gyp/0.12.0/deps/v8/include/v8.h:5809:4: note:   candidate expects 2 arguments, 1 provided
../src/binding.cc:92:8: error: ‘struct {anonymous}::write_req’ has no member named ‘req’
   req->req.data = req;
        ^
../src/binding.cc:94:33: error: ‘uv_default_loop’ was not declared in this scope
   uv_queue_work(uv_default_loop(), &req->req, write_async, (uv_after_work_cb)write_after);
                                 ^
../src/binding.cc:94:42: error: ‘struct {anonymous}::write_req’ has no member named ‘req’
   uv_queue_work(uv_default_loop(), &req->req, write_async, (uv_after_work_cb)write_after);
                                          ^
../src/binding.cc:94:47: error: ‘write_async’ was not declared in this scope
   uv_queue_work(uv_default_loop(), &req->req, write_async, (uv_after_work_cb)write_after);
                                               ^
../src/binding.cc:94:61: error: ‘uv_after_work_cb’ was not declared in this scope
   uv_queue_work(uv_default_loop(), &req->req, write_async, (uv_after_work_cb)write_after);
                                                             ^
../src/binding.cc:94:89: error: ‘uv_queue_work’ was not declared in this scope
   uv_queue_work(uv_default_loop(), &req->req, write_async, (uv_after_work_cb)write_after);
                                                                                         ^
../src/binding.cc:96:20: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
   return Undefined();
                    ^
In file included from ../src/binding.cc:4:0:
/home/bananapi/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: declared here
   friend Handle<Primitive> Undefined(Isolate* isolate);
                            ^
../src/binding.cc: At global scope:
../src/binding.cc:99:19: error: variable or field ‘write_async’ declared void
 void write_async (uv_work_t *req) {
                   ^
../src/binding.cc:99:19: error: ‘uv_work_t’ was not declared in this scope
../src/binding.cc:99:30: error: ‘req’ was not declared in this scope
 void write_async (uv_work_t *req) {
                              ^
../src/binding.cc:104:19: error: variable or field ‘write_after’ declared void
 void write_after (uv_work_t *req) {
                   ^
../src/binding.cc:104:19: error: ‘uv_work_t’ was not declared in this scope
../src/binding.cc:104:30: error: ‘req’ was not declared in this scope
 void write_after (uv_work_t *req) {
                              ^
In file included from ../src/binding.cc:5:0:
/home/bananapi/.node-gyp/0.12.0/src/node.h:405:3: error: expected ‘}’ at end of input
   }
   ^
/home/bananapi/.node-gyp/0.12.0/src/node.h:427:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)
   ^
../src/binding.cc:159:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(binding, Initialize)
 ^
../src/binding.cc:25:15: warning: ‘v8::Handle<v8::Value> {anonymous}::Open(const int&)’ defined but not used [-Wunused-function]
 Handle<Value> Open (const Arguments& args) {
               ^
../src/binding.cc:78:15: warning: ‘v8::Handle<v8::Value> {anonymous}::Write(const int&)’ defined but not used [-Wunused-function]
 Handle<Value> Write (const Arguments& args) {
               ^
binding.target.mk:92: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/bananapi/code/node-web-audio-api/node_modules/speaker/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.4.103
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bananapi/code/node-web-audio-api/node_modules/speaker
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing speaker@0.0.10

> web-audio-api@0.2.1 prepublish /home/bananapi/code/node-web-audio-api
> gulp

[15:27:03] Using gulpfile ~/code/node-web-audio-api/gulpfile.js
[15:27:03] Starting 'default'...
[15:27:09] Finished 'default' after 6.49 s
[bananapi@lemaker node-web-audio-api]$ 
```

**Comment by sebpiq** [comment]
Not totally sure, but it seems to be node-speaker (an optional dependency of node-web-audio-api) which fails. As node-speaker is optional, have you tried to use the library anyways after these errors? You could for example create a couple of nodes, and plug the output of the AudioContext to a file (see https://github.com/sebpiq/node-web-audio-api#streaming-audio) to see if you get any result ... If you do, then the error is only node-speaker, and we'll have to see there why it refuses to compile. Might be that it doesn't support node 0.12 yet. Apparently the c++ changes between 0.10 and 0.12 are very important.

**Comment by bburdette** [comment]
ok, didn't realize that speaker was separate from this project.  there's a bug there that might have something to do with this issue, although the C++ errors are not exactly the same.  Maybe its the same problem, changes in the underlying v8 or whatever.  

https://github.com/TooTallNate/node-speaker/issues/46

I'm pretty much a noob with js so creating a file node and etc is a little beyond me in just a few minutes.  Got to do other things right now but I'd like to get this working at some point.  I guess it might be possible to just stream the audio to mplayer, possibly with more latency than with speaker?

**Comment by sebpiq** [comment]
Ok just made a push, you can pull it, and try this (if you have alsa) new example I wrote :

```javascript
node test/manual-testing/AudioContext-stdout.js | aplay -f cd
```

Basically we just write generated audio to stdout and pipe to another process which will read the audio.

**Comment by bburdette** [comment]
Thanks for setting that up!

I rebuilt with 

> npm install
> gulp default

Then I tried it with just aplay directly, got sound.  With node I get an error:

```
[bburdette@nixosthe1:~/code/webaudiotest/node-web-audio-api]$ node --version
v0.12.0

[bburdette@nixosthe1:~/code/webaudiotest/node-web-audio-api]$ aplay test/manual-testing/sounds/powerpad.wav 
Playing WAVE 'test/manual-testing/sounds/powerpad.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo

[bburdette@nixosthe1:~/code/webaudiotest/node-web-audio-api]$ node test/manual-testing/AudioContext-stdout.js | aplay -f cd
Speaker is not available, fix this if you need sound playback.
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
/home/bburdette/code/webaudiotest/node-web-audio-api/build/AudioBuffer.js:24
        return chArray.slice.apply(chArray, sliceArgs)
                            ^
TypeError: Cannot read property 'apply' of undefined
    at /home/bburdette/code/webaudiotest/node-web-audio-api/build/AudioBuffer.js:24:29
    at Array.map (native)
    at AudioBuffer.proto$0.slice (/home/bburdette/code/webaudiotest/node-web-audio-api/build/AudioBuffer.js:23:26)
    at AudioBufferSourceNode.this$0._dsp (/home/bburdette/code/webaudiotest/node-web-audio-api/build/AudioBufferSourceNode.js:49:35)
    at AudioBufferSourceNode.proto$0._tick (/home/bburdette/code/webaudiotest/node-web-audio-api/build/AudioBufferSourceNode.js:86:17)
    at AudioOutput.proto$0._tick (/home/bburdette/code/webaudiotest/node-web-audio-api/build/audioports.js:154:33)
    at /home/bburdette/code/webaudiotest/node-web-audio-api/build/audioports.js:92:21
    at Array.map (native)
    at AudioInput.proto$0._tick (/home/bburdette/code/webaudiotest/node-web-audio-api/build/audioports.js:91:56)
    at AudioDestinationNode.proto$0._tick (/home/bburdette/code/webaudiotest/node-web-audio-api/build/AudioDestinationNode.js:15:28)

```

**Comment by sebpiq** [comment]
Alright ... I've just installed node 0.12 and tried to install node-web-audio-api : 

- I get the same bugs as you with node-speaker and I am not in position to fix those, so I think I'll just remove node-speaker from the dependencies (see #33)

- The tests don't pass with node 0.12, so there is indeed bugs which need fixing, thanks for finding those out :) I've created a ticket (see #34)

**Comment by sebpiq** [comment]
meanwhile, if you really want to try you can install node 0.10! It should work fine. I recommend using nvm (https://github.com/creationix/nvm) to install different versions of node. I had it installed on arch linux and it worked like a charm!

**Comment by bburdette** [comment]
cool, I'll check in to v0.10 when I get a chance, hopefully soon.
