### ISSUE TITLE
Error: Cannot find module 'speaker'

### ISSUE THREAD

**Issue by praya** [sebpiq/node-web-audio-api#47]
<pre>node test/manual-testing/AudioContext-sound-output.js
module.js:339
    throw err;
    ^

Error: Cannot find module 'speaker'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/mbp/Downloads/node-web-audio-api-master/test/manual-testing/AudioContext-sound-output.js:5:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
</pre>

**Comment by sebpiq** [comment]
yes, to run this test you need to install `speaker`. You can do it with `npm install speaker`
